title: Luca Vellage
description: Data projects & writing
url: "https://lucavellage.github.io"
baseurl: ""

author: Luca Vellage
email: email

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock